# platform :ios, '9.0'
use_frameworks!

def library
    pod 'KissXML'
end

def socket
    pod 'CocoaAsyncSocket'
end

target '34.VPNDemo' do
socket
end

target 'PacketProcess' do
   socket
end

target 'PotatsoBase' do
socket
end

target 'VPNTunnelDemo' do
socket
end

target "PotatsoLibrary" do
    library
end
