# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '50.ObjectMapperDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 50.ObjectMapperDemo
pod 'ObjectMapper', '~> 3.5'

end
